# Generated by Django 2.0.6 on 2018-08-18 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_many', '0003_auto_20180812_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='publications',
            field=models.ManyToManyField(related_name='articles', to='test_many.Publication'),
        ),
    ]
