# Generated by Django 2.0.6 on 2018-09-01 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_many', '0005_author_blog_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
