# Generated by Django 2.0.6 on 2018-09-02 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_many', '0006_author_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThemeBlog',
            fields=[
                ('blog_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='test_many.Blog')),
                ('theme', models.CharField(max_length=200)),
            ],
            bases=('test_many.blog',),
        ),
    ]
