# Generated by Django 2.0.6 on 2018-09-02 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_many', '0008_auto_20180902_0926'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='author',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, to='test_many.Author'),
            preserve_default=False,
        ),
    ]
