# Generated by Django 2.0.6 on 2018-09-07 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_many', '0010_auto_20180902_1021'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['name']},
        ),
    ]
