# Generated by Django 2.0.6 on 2018-09-17 20:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_many', '0014_auto_20180915_0954'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('home_group', models.CharField(max_length=5)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='place',
        ),
        migrations.RemoveField(
            model_name='themeblog',
            name='blog_ptr',
        ),
        migrations.RemoveField(
            model_name='waiter',
            name='restaurant',
        ),
        migrations.AlterField(
            model_name='entry',
            name='mod_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 17, 20, 13, 28, 717309)),
        ),
        migrations.DeleteModel(
            name='Place',
        ),
        migrations.DeleteModel(
            name='Restaurant',
        ),
        migrations.DeleteModel(
            name='ThemeBlog',
        ),
        migrations.DeleteModel(
            name='Waiter',
        ),
    ]
