# Generated by Django 2.0.6 on 2018-09-17 20:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_many', '0015_auto_20180917_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='mod_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 17, 20, 14, 4, 166200)),
        ),
    ]
