# Generated by Django 2.0.6 on 2018-09-17 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_many', '0016_auto_20180917_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='mod_date',
            field=models.DateTimeField(),
        ),
    ]
