# Generated by Django 2.0.6 on 2018-07-15 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0002_auto_20180715_1021'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
